inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'lib/romajic/cli.rb'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '*.gemspec'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/romajic/cli.rb'

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'lib/romajic/cli.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/romajic/cli.rb'

Style/ConditionalAssignment:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false

Style/YodaCondition:
  Exclude:
    - 'lib/romajic/cop.rb'
