AllCops:
  DisplayCopNames: true

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '*.gemspec'

Metrics/LineLength:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false
